[2019-12-12 21:09:13,017] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 4 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 21:19:13,013] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 21:29:13,013] INFO [GroupMetadataManager brokerId=0] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2019-12-12 21:32:54,598] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-12-12 21:32:54,622] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-12-12 21:32:54,625] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-12-12 21:32:54,643] INFO [GroupCoordinator 0]: Member consumer-2-226366d8-61da-4b14-988e-a6576284757e in group group_json has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,644] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json in state PreparingRebalance with old generation 1 (__consumer_offsets-2) (reason: removing member consumer-2-226366d8-61da-4b14-988e-a6576284757e on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,647] INFO [GroupCoordinator 0]: Member consumer-4-4fcdfe88-55c5-4e7d-8c1a-dfba3876c4e3 in group group_json_fitness has left, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,647] INFO [GroupCoordinator 0]: Preparing to rebalance group group_json_fitness in state PreparingRebalance with old generation 1 (__consumer_offsets-49) (reason: removing member consumer-4-4fcdfe88-55c5-4e7d-8c1a-dfba3876c4e3 on LeaveGroup) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,648] INFO [GroupCoordinator 0]: Group group_json_fitness with generation 2 is now empty (__consumer_offsets-49) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,648] INFO [GroupCoordinator 0]: Group group_json with generation 2 is now empty (__consumer_offsets-2) (kafka.coordinator.group.GroupCoordinator)
[2019-12-12 21:32:54,922] WARN Session 0x1000010a7f90000 for server localhost/127.0.0.1:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.io.IOException: Connection reset by peer
	at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
[2019-12-12 21:32:55,027] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 21:32:55,028] INFO [ZooKeeperClient Kafka server] Connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 21:32:56,641] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 21:32:56,644] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 21:32:56,745] INFO [ZooKeeperClient Kafka server] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-12-12 21:32:58,643] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 21:32:58,643] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-12-12 21:33:00,473] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-12-12 21:33:00,476] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
